files:
  include: 'Resources/Private/**/*.scss'
rules:
  property-sort-order: 0
  indentation:
    - 1
    -
      size: 4
  class-name-format:
    - 1
    -
      convention: camelcase
  hex-notation: 0
  hex-length: 0
  nesting-depth:
    - 1
    - max-depth: 4
  no-url-protocols: 0
  no-url-domains: 0
  single-line-per-selector: 0
  force-pseudo-nesting: 0
  force-element-nesting: 0
  final-newline: 1
  force-attribute-nesting: 0
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
  no-vendor-prefixes:
    - 1
    -
      ignore-non-standard: true
